apiVersion: v2
name: billing-service
description: Billing service

type: application
version: 0.0.3
appVersion: 3

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - billing-database

