apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: billing-ingress
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - backend:
          serviceName: billing-service
          servicePort: 8000
        path: /billing/accounts

