replicaCount: 1

fullnameOverride: "auth"

image:
  repository: neversleeps/otus-arch-homework-05-auth
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  persistence:
    size: 0.1Gi
  service:
    port: "5432"

ingress:
  enabled: false
  hosts:
    - host: arch.homework
      paths: ["/auth"]
