apiVersion: v1
kind: Secret
metadata:
  name: notification-messaging-secret
  namespace: dev
type: Opaque
data:
  kafkaUrl: {{ required "Please specify messaging.kafkaUrl" .Values.messaging.kafkaUrl | b64enc }}

