replicaCount: 1

postgresql:
  fullnameOverride: stock-postgres
  postgresqlUsername: stock-architect
  postgresqlPassword: stock-architect
  postgresqlDatabase: stock-architect
  service:
    type: NodePort
    port: 5434
  persistence: 
    enabled: true
    size: 1Gi
  resources: 
    requests: 
      memory: 256Mi
      cpu: 250m

db: 
  host: "stock-postgres"
  database: "stock-architect"
  username: "stock-architect"
  password: "stock-architect"
  port: "5434"

metrics:
  serviceMonitor:
    enabled: true

ingress:
  enabled: false
  hosts:
    - host: arch.homework
      paths: ["/"]