apiVersion: v1
kind: Service
metadata: 
  name: notification-service
  labels: 
    app: notification-service
spec: 
  selector: 
    app: notification-app
  ports: 
  - protocol: TCP
    port: 8000
    targetPort: web
    name: web
  type: NodePort