apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: stock-app
  template: 
    metadata:
      labels: 
        app: stock-app
    spec: 
      containers: 
      - name: stock-backend
        image: neversleeps/stock-service-09:1
        ports: 
        - name: web
          containerPort: 8004
        livenessProbe:
          httpGet:
            port: 8004
            path: /
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 8004
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5
        env: 
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: database
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: port
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stock-secret
                key: password