apiVersion: v1
kind: Service
metadata: 
  name: stock-service
  labels: 
    app: stock-service
spec: 
  selector: 
    app: stock-app
  ports: 
  - protocol: TCP
    port: 8000
    targetPort: web
    name: web
  type: NodePort