apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: dev
type: Opaque
data:
  host: {{ required "Please specify redisDb.host" .Values.redisDb.host | b64enc }}
  password: {{ required "Please specify redisDb.password" .Values.redisDb.password | b64enc }} 
  port: {{ required "Please specify redisDb.port" .Values.redisDb.port | b64enc }} 
