apiVersion: v1
kind: Service
metadata: 
  name: delivery-service
  labels: 
    app: delivery-service
spec: 
  selector: 
    app: delivery-app
  ports: 
  - protocol: TCP
    port: 8000
    targetPort: web
    name: web
  type: NodePort