apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: notification-ingress
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - backend:
          serviceName: notification-service
          servicePort: 8000
        path: /notifications
