version: '2.0'
services:
  db:
    container_name: notification_postgres
    image: postgres:11
    ports:
      - "5438:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: notification
      POSTGRES_USER: notification
      POSTGRES_DB: notification