controller:
  kind: DaemonSet

  reportNodeInternalIp: true

  daemonset:
    useHostPort: true
    hostPorts:
      http: 80
      https: 443

  service:
    type: NodePort

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true