apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |-
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.platform=postgres
    spring.datasource.url={{ printf "jdbc:postgresql://%s-postgresql:%s/%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase }}
    spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true