server:
  port: 8004

app:
  database:
    db: ${DB_NAME:stock}
    host: ${DB_HOST:postgres}
    port: ${DB_PORT:5434}
    username: ${DB_USERNAME:stock}
    password: ${DB_PASSWORD:stock}

spring:
  datasource:
    url: jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.db}
    username: ${app.database.username}
    password: ${app.database.password}
    driver-class-name: org.postgresql.Driver
    platform: postgresql