{
 "title": "Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Потребление памяти подами",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Потребление ЦПУ подами",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Среднее время ответа приложения",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m]))/sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "Среднее время ответа"
    }
   ]
  },
  {
   "title": "Количество запросов к приложению",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "количество запросов"
    }
   ]
  },
  {
   "title": "Количество ошибочных запросов к приложению",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"[345]..\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Перезагрузка под куба",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, container) (rate(kube_pod_container_status_restarts_total[1m]))"
    }
   ]
  },
  {
   "title": "RPS [direct]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(user_service_requests_seconds_count[2m]))"
    }
   ]
  },
  {
   "title": "RPS Total [ingress]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(nginx_ingress_controller_request_duration_seconds_count[2m]))"
    }
   ]
  },
  {
   "title": "Latency [direct]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri, quantile) (user_service_requests_seconds) * 1000"
    },
    {
     "expr": "sum by (method, uri) (user_service_requests_seconds_max) * 1000"
    }
   ]
  },
  {
   "title": "Latency [ingress]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Error Rate [direct]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(user_service_requests_seconds_count{status=~\"4..\"}[2m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(user_service_requests_seconds_count{status=~\"5..\"}[2m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Error Rate [ingress]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"4..\"}[2m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5..\"}[2m]))",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}