replicaCount: 1

postgresql:
  fullnameOverride: billing-postgres
  postgresqlUsername: billing-architect
  postgresqlPassword: billing-architect
  postgresqlDatabase: billing-architect
  service:
    type: NodePort
    port: 5436
  persistence: 
    enabled: true
    size: 1Gi
  resources: 
    requests: 
      memory: 256Mi
      cpu: 250m

db: 
  host: "billing-postgres"
  database: "billing-architect"
  username: "billing-architect"
  password: "billing-architect" 
  port: "5436"

metrics:
  serviceMonitor:
    enabled: true

# ingress:
#   enabled: false
#   hosts:
#     - host: arch.homework
#       paths: ["/"]