server:
  port: 8002

app:
  database:
    db: ${DB_NAME:notification}
    host: ${DB_HOST:postgres_notification}
    port: ${DB_PORT:5438}
    username: ${DB_USERNAME:notification}
    password: ${DB_PASSWORD:notification}

spring:
  datasource:
    url: jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.db}
    username: ${app.database.username}
    password: ${app.database.password}
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:25}
      pool-name: ${HIKARI_POOL_NAME:HikariPostgresPool}
      minimum-idle: ${HIKARI_MIN_IDLE:10}

kafka:
  bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS:}

logging:
  level:
    com:
      zaxxer: WARN