version: '2.0'
services:
  db:
    container_name: delivery_postgres
    image: postgres:11
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: delivery
      POSTGRES_USER: delivery
      POSTGRES_DB: delivery