apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  dbusername: {{ printf "%s" .Values.postgresql.postgresqlUsername | b64enc | quote }}
  dbpassword: {{ printf "%s" .Values.postgresql.postgresqlPassword | b64enc | quote }}